### ISSUE TITLE
Exploring cultural expectations re: privacy and security

### ISSUE THREAD

**Issue by samuelweiler** [w3c/chinese-ig-charter#13]
I expect the Chinese Web community has (quite) different expectations around privacy and (perhaps to a lesser degree) security than western cultures.  Is there interest in the IG in exploring that specifically?  Is there utility in it?

**Comment by xfq** [comment]
The group has not discussed this before, but I can discuss it with the co-chairs, as a potential IG area in the future.

**Comment by xfq** [comment]
I asked the co-chairs at the monthly Chairs' call, but there was no feedback, so it seems that there's no interest in in exploring it, at least for now. That said, you are welcome to open an issue in https://github.com/w3c/chinese-ig/issues to solicit feedback from other IG participants.

**Comment by xfq** [comment]
Closing.
